[package]
name = "insomnia"
version = "0.1.0"
authors = ["Ben Merritt <blm768@gmail.com>"]
edition = "2018"

[target.'cfg(target_os = "linux")'.dependencies.logind-dbus]
version = "0.1"
path = "../logind-dbus"
